version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: ls -al ~

      - run:
          name: get aws
          command: sudo apt-get update && sudo apt-get install -y awscli

      - run: zip -r tabletop.zip .
      - run: cat ~/.aws/credentials
      - run: cat ~/.aws/config

      - run:
          name: ls
          command: ls -al

      - run:
          name: deploy to s3
          command: aws s3 cp tabletop.zip s3://melen-tabletop/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job